name: envfriendly
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_local_notifications: ^17.2.3
  rxdart: ^0.28.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  firebase_analytics: ^11.3.3
  fl_chart: ^0.69.0
  flutter_slidable: ^3.1.1
  flutter_staggered_animations: ^1.1.1
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  generate: true
